#!/bin/bash
export STACK_NAME='base'
export REGION_DNS='cn-north-1.base.bwtsi.cn'
export HOSTNAME='ci-components-slave'
export INSTANCE_ID='i-0bb963deb7ed5b718'
export DISK_ENCRYPTION_KEY='6eb74ycgfs4cezffb5ztr5e4idkmjq'
export ROLE='base'
export ENVIRONMENT='base'
mkdir -p /etc/tradeshift
echo ${STACK_NAME} > /etc/tradeshift/stackname
echo ${HOSTNAME}-$INSTANCE_ID > /etc/hostname; hostname -F /etc/hostname
sed -i -e '/^127.0.0.1/d' /etc/hosts; echo 127.0.0.1 ${HOSTNAME}-$INSTANCE_ID.${REGION_DNS} ${HOSTNAME}-$INSTANCE_ID localhost >> /etc/hosts
#echo $INSTANCE_ID | openssl dgst -sha256 -hmac '${DISK_ENCRYPTION_KEY}' | sed 's/^.*= //' > /dev/shm/encrypted-disk.luks.key && chmod 400 /dev/shm/encrypted-disk.luks.key
echo "nameserver 172.16.30.71" >> /etc/resolv.conf
echo "nameserver 172.16.30.74" >> /etc/resolv.conf

sed -i -e 's@http://archive.ubuntu.com@http://cn.archive.ubuntu.com@g' /etc/apt/sources.list
sed -i -e 's@http://security.ubuntu.com@http://mirrors.aliyun.com@g' /etc/apt/sources.list
sed -i -e '/^deb-src/d' /etc/apt/sources.list
touch /tmp/client.key
cat > /tmp/client.key << EOF
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAtDaBK1LL1cAxiA0NwNfJVYc915dxDfhCN9eoX3gymWMrVLu5
R3M7XakuIXGX6FDHj0VG5i2CKofZQIV1eV1D9GYz9VWh9vvsclE93HGBgvyTg/IO
fFH3D3ypMQrOfIzhM0KOnlYvcYAQKFo0OKpO2Zp7O+2m4FeZ2tEu6/kdllhb7YIG
mOb0mypJNkpBQ0omAWh2fAxOdNyXuekr9RSCVlD+GWQkbN5A4+2atUi7b0IUpB1B
9L2kIpWq8eotZSd6MpAAACrjEWcB/2cde1iGKUxrJtaY8RYXKNUBqUWH8xj/Tl/q
1oTjKsTXcyOjGEHcAOkMt4HEze4Tijo9AlbicQIDAQABAoIBAQCphkRITuC0uNFf
XHg9mkApFsnUDwAo1grkoRgght+Cb0mJsfX/AqUr3EQq7cKqpaK0YcTqLpEuFREH
owP5IQUV2TazaNStlBq/BzGcN6JPZ+4UxxVdWXWBuhEmszW+8H/ASrICvKxwprmM
XB6X143JIYsfutWqYH242+K51GRC0lJ/js8bjSn/cpVmyWOEqUWnCmJJ2+YzyooV
uA3EkfKMp8JrPvrl+W81V2HeWfIIYNVA0pnwR5xwBzxMvsIFdaSD9XhejEeNA506
Z8NIPw6xViLedz1g2kvuUixQnu8wIRnWthPiCJxPvp6hcwyr5OpYCpmiuG8Zy0Wh
Ubn1NhsJAoGBAOhFgsSJux3WmYF4pV5Rx2gqrOmBmKCHaMP1pKfLirz77zj+/8be
OIeefYoDdJ+gkaUDS4FqB44dhgHBubykXt7/qjEEYtAJMYmhXWd0U9FZGnSuZuAh
38CouCmefOfK3YClsORcDJLkAZxmSH2yrfCZIhesEvmi8NvTEQwQCro/AoGBAMaf
h2gWC+7mQ71x/bTmi35hIEjAjquUGtC3ugIrrplElIRagjzdb1zooKTlxLnshnkB
g7L1p+xQVqzVjY1lWxjplwjk0u/ScBPC2PqZ8JZ7YbDBmCBJ5xBc0xOkuBD711y1
hgNUkownUxQ/zMcsWaJq4zqEs4rvv5bJveLPRFdPAoGABz6DwZV6HIgg6YTVw4dR
bNJH6lB8biVLAzGaHRGgFhzVbTWmzJEJulEbIT7SWFgtsrPTmwmviqMpFszv+g42
V0YqDLVST6K5xM0fmKZsJs9cn98AnmTwEZYxiDrFMoWFOwnv5m9ohPxPgI1AHYuB
GUvtYEehn9+RG4oNsg6eBwkCgYB838Eu1GWOPiCqk2cxe5yJySCV/NH113iAbnI4
eSQdYjuJdqnZAFLKc8rDwV1MkwL8QtJ9CesYLG5B3UVQdz+tyvZU9iAT/RbPpbnq
3CuhQFLr4Nr2ud/WrrVZ7T54Fw2QUOO/ZkV4biTSX0YslpqH/XF80f9bQ14NvCpw
1WSfCwKBgE1l6bxE6aXNolJ/9GJFwXfvmOvRSlNVJqw/CtQFmOyaQfbTF9a22oFR
WLPt1z//qUUKtfRMVhFLnM9Nptx4MX9KECnn1l3R7Sppr5+nlyOIO4Q/tEI6CsT8
f5hPiSo+L9GssxWTQ1ZJi8lawzGC/OAmCzycoRCnP78hOQpL6tTz
-----END RSA PRIVATE KEY-----
EOF

touch /tmp/bwtsi_ca.cert
cat > /tmp/bwtsi_ca.cert << EOF
-----BEGIN CERTIFICATE-----
MIIEZjCCA06gAwIBAgIBATANBgkqhkiG9w0BAQsFADCBrzELMAkGA1UEBhMCQ04x
EDAOBgNVBAgTB0JlaWppbmcxEDAOBgNVBAcTB0JlaWppbmcxGzAZBgNVBAoTEkJh
aXdhbmcgVHJhZGVzaGlmdDEnMCUGA1UECxMeQmFpd2FuZyBUcmFkZXNoaWZ0IEVu
Z2luZWVyaW5nMTYwNAYDVQQDEy1CYWl3YW5nIFRyYWRlc2hpZnQgUm9vdCBDZXJ0
aWZpY2F0ZSBBdXRob3JpdHkwIBcNMTYwNTEzMTE0MDAwWhgPMjA2NjA1MTMxMTQw
MDBaMIGvMQswCQYDVQQGEwJDTjEQMA4GA1UECBMHQmVpamluZzEQMA4GA1UEBxMH
QmVpamluZzEbMBkGA1UEChMSQmFpd2FuZyBUcmFkZXNoaWZ0MScwJQYDVQQLEx5C
YWl3YW5nIFRyYWRlc2hpZnQgRW5naW5lZXJpbmcxNjA0BgNVBAMTLUJhaXdhbmcg
VHJhZGVzaGlmdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eTCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAMMMZB54Btgl6ZSbosQMT0VrKDt7m+vOkuni
7VBJSyz5BAV6lqPrfbFcXxSMBPbDVdtjBnJe/nn+0W3jOySZhH1D+QEJKYwZWUF5
5KhZOMUmH0XJcIEjbKlG4ljsp0MZKYpO49HUGfhxmx8HofB+vmlnDn0ft1X/QaNy
9wjIz8+fjpD3rtmOAKD5bshJQd4X8RsZtFmzSjN4TgXD3GIcz+ua1MmP4Y90B0dt
1qPgJVZ2aDgKRBt01ccsB5N8l2R3E0L6T9FEFgUzHn6IP+HCX/ChlDMINw4kIUbD
PObVRAIPmKRTD69Jlg8VzZyztRI9Bu/xvqY5HU/NMyW/PywqvSMCAwEAAaOBiDCB
hTAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIBhjAxBgNVHR8EKjAoMCagJKAihiBo
dHRwczovL3BraS5id3RzaS5jbi9CV1RTX0NBLmNybDA1BggrBgEFBQcBAQQpMCcw
JQYIKwYBBQUHMAGGGWh0dHBzOi8vcGtpLmJ3dHNpLmNuL29jc3AwDQYJKoZIhvcN
AQELBQADggEBAISFBd43KSbfPa+O4GlP5uxzuovF+XWusMGkR7IninlfAb9ENKJD
g/C0uPWZyYwBXcHbiUFCBmFgeJ1F1wkNqjptRjcCFZS5D+mh0wKKR1A5m04Ilqf3
DqFc2Kd0XlOs/lcW5hjY1Br74SdJ/1HWfcqrp8C9oXH5Dpyb0CPJlGzLVBprp1Ej
Ey5AMAxyrArJH3t575RJ5Wa3FDYYoiIUw6YNyZhYRyMD2uj56ZuZlIk5TFpDxQfd
ylCXTswL/KjtXL9QeZGfSehsVsSfvldZ/oqQjZEt5D1CUWoFy4l3NVcJJFTxjgQ5
M2Rl9BnCW086nGEFFgtKv5F7icdL7BrSQg4=
-----END CERTIFICATE-----
EOF
touch /tmp/puppet.conf
cat > /tmp/puppet.conf << EOF
[main]
environment = base

[agent]
runinterval = 15m
server = puppet.bwtsi.cn
certname = base.base.bwtsi.cn
node_name = facter
node_name_fact = fqdn
EOF

touch /tmp/package_bwtsi.key
## Configure APT Source
echo "Adding aliyun and bwtsi package repository:"
cat > /tmp/package_bwtsi.key << EOF
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQENBFdEEV0BCADM6Lu3nXrJASsrhif+k8dEpZM6bydNyHR+28tfEPnCo04PKL3x
pQs50BUWtnbyI1M4w3XeF7+0iNm/Ih6oLxoFvzCyVJyF8TbpRnT3FYLXNXwN07Rh
xKiMpC0sdgtrBxVE7NlyBHBbMO8mluA8wfo1Fe5ZhUj8HYg8rPb/t/8eHlji1+OX
SW6TMt6q/s6ssDND97h4wn1lNNeAJ74j3n7lSu+wiVuiVeoTD18wdkp5UMN/dIDk
rOcRJ4ifRjgjAepbYjjFUd4kNkm4xLpBxF6QONRI5steMPSbbGXPj8Q/MVZYYYgK
skagA6gCz384PkAGyfzEbKJZ4YgH57SoC2xRABEBAAG0Pll1YW56aGVuIFpob3Ug
KEdQRyBrZXkgZm9yIEJXVFMgYXB0IHJlcG8pIDxqb2VAdHJhZGVzaGlmdC5jb20+
iQE+BBMBAgAoBQJXRBFdAhsDBQkJZgGABgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIX
gAAKCRAF31VXcZi+T4rwCACPm7kwIv66Su3uA83ZR8NGc/eq6B807Y8Vjf6zjf91
jaFShRdsSXnErWUkSMpzUYj4xmMBoLZhj1EBi2+UfGMl5FYa6tKOQ9EdVdAUE7ed
TCLvoVqcSW1V8V5YYs7oOCExhy1AW39lB9xZh/jhiQmHIUqroLYiwAGw1VBnfthY
YCpomOW//njWQ7SF5Vy3qcN3UJpgJtcXwEhq8R4PWdkFcgZYkF8wzqMwrB7K385i
LhilRNFGebEiq3tiTLebD5Vqd0+hctfwWds7IPHEsnsyBZNDPk+0oYXD4AEt/1Aa
KmU2Pz75V2ocfml5QqHHq+Fs6LzfhTEB6kK1iRJFvAuEuQENBFdEEV0BCADCNkjO
bz0LTdRX3kOOgmBLwAiAe2PsjSuAAaegt27x+l+zhhcI5OdTLXgtAvD3nuGyyOa4
k8Nuxawpn3zK3PuTN10PRCuRwQtY85b0q2CET/ahaVojYfTnnSpYGRNIT69behQ6
b1utyH2f3bTJmlh09XdPhH4MNztZqrBJ8/eDiP6pN8KMutrrgbLo2c+vXMtaND39
rFmvRjH+a12iz7WqfwxrZSGTs60xw93bfvN5uVq9v3cTgUL2jrVzLNGLNJepKltZ
XEU0fsqkXzxZuAjYV9Gfo6T4PkTvV4OnWwAln4xqMHqaAMpTRSGpJHfzzKvMBn/u
+ymPUBzQu5zBK2v7ABEBAAGJASUEGAECAA8FAldEEV0CGwwFCQlmAYAACgkQBd9V
V3GYvk8Vdgf8DxZbapewwRFXQbTiODL7ISoJH413qFntYvczAuRcIufEfvdZF0hl
ulY/lhN7HBLD2cLXPPSHO8oBMXNYghTgY68Jc6oRnBa534I+UcRmR0Ifi7TLjCPe
5R99LqtK+JoqTWCP1JeQIWCPK1Q72UQ06SUr6YpghD4kp/VTLm3CEziKBczBF+uy
C7RCOq11DiT7PPyOIuT76HwJd6eN57DBnq6R0n75rfLET48wZkpTyTsBg6ffswQx
lSoCHW/Ko8HdxjUOFBgEKLl7zlAxmf6T4lu3zmUvl9vA3oGrfDPAq4DLbsjZTYqj
M7bamLgmmd/ROLC6TinVbgrcXu3U9AS4ZA==
=qUGC
-----END PGP PUBLIC KEY BLOCK-----
EOF
apt-key add /tmp/package_bwtsi.key

touch /etc/apt/sources.list.d/bwts.list
cat > /etc/apt/sources.list.d/bwts.list << EOF
deb [arch=amd64] http://pkg.bwtsi.cn trusty main
EOF

touch /etc/apt/sources.list.d/163.list
cat > /etc/apt/sources.list.d/163.list << EOF
deb http://mirrors.163.com/ubuntu/ trusty main restricted universe multiverse
deb http://mirrors.163.com/ubuntu/ trusty-security main restricted universe multiverse
deb http://mirrors.163.com/ubuntu/ trusty-updates main restricted universe multiverse
deb http://mirrors.163.com/ubuntu/ trusty-proposed main restricted universe multiverse
deb http://mirrors.163.com/ubuntu/ trusty-backports main restricted universe multiverse
EOF
touch /tmp/client.cert
cat > /tmp/client.cert << EOF
-----BEGIN CERTIFICATE-----
MIIEsDCCA5igAwIBAgIBQzANBgkqhkiG9w0BAQsFADCBrzELMAkGA1UEBhMCQ04x
EDAOBgNVBAgTB0JlaWppbmcxEDAOBgNVBAcTB0JlaWppbmcxGzAZBgNVBAoTEkJh
aXdhbmcgVHJhZGVzaGlmdDEnMCUGA1UECxMeQmFpd2FuZyBUcmFkZXNoaWZ0IEVu
Z2luZWVyaW5nMTYwNAYDVQQDEy1CYWl3YW5nIFRyYWRlc2hpZnQgUm9vdCBDZXJ0
aWZpY2F0ZSBBdXRob3JpdHkwHhcNMTYwOTEzMDIwOTAwWhcNMTcwOTEzMDIwOTAw
WjCBlDELMAkGA1UEBhMCQ04xEDAOBgNVBAgTB0JlaWppbmcxEDAOBgNVBAcTB0Jl
aWppbmcxGzAZBgNVBAoTEkJhaXdhbmcgVHJhZGVzaGlmdDEnMCUGA1UECxMeQmFp
d2FuZyBUcmFkZXNoaWZ0IEVuZ2luZWVyaW5nMRswGQYDVQQDExJiYXNlLmJhc2Uu
Ynd0c2kuY24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC0NoErUsvV
wDGIDQ3A18lVhz3Xl3EN+EI316hfeDKZYytUu7lHcztdqS4hcZfoUMePRUbmLYIq
h9lAhXV5XUP0ZjP1VaH2++xyUT3ccYGC/JOD8g58UfcPfKkxCs58jOEzQo6eVi9x
gBAoWjQ4qk7Zmns77abgV5na0S7r+R2WWFvtggaY5vSbKkk2SkFDSiYBaHZ8DE50
3Je56Sv1FIJWUP4ZZCRs3kDj7Zq1SLtvQhSkHUH0vaQilarx6i1lJ3oykAAAKuMR
ZwH/Zx17WIYpTGsm1pjxFhco1QGpRYfzGP9OX+rWhOMqxNdzI6MYQdwA6Qy3gcTN
7hOKOj0CVuJxAgMBAAGjge8wgewwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUDtOl
so8wXbkefS9+ot2rjc8MzmEwCwYDVR0PBAQDAgSwMBMGA1UdJQQMMAoGCCsGAQUF
BwMCMDEGA1UdHwQqMCgwJqAkoCKGIGh0dHBzOi8vcGtpLmJ3dHNpLmNuL0JXVFNf
Q0EuY3JsMDUGCCsGAQUFBwEBBCkwJzAlBggrBgEFBQcwAYYZaHR0cHM6Ly9wa2ku
Ynd0c2kuY24vb2NzcDARBglghkgBhvhCAQEEBAMCB4AwHgYJYIZIAYb4QgENBBEW
D3hjYSBjZXJ0aWZpY2F0ZTANBgkqhkiG9w0BAQsFAAOCAQEAIgLY/a+v0eiutHWX
McLf2MwS0OuKlnosEsIdOz2GohEeGtTCWtvXqSc2TYPYkjz7MLBb9S5ZPohwxcww
4Q1g27OkT3kU67OrbWex9n6ZYhJJEZBnIqfCtYXuZchZPdXph+tOTPQh4LlltTs/
VWUwm9h3g2R3INcTDvctpjao0VjWNJBZi9fhr/vjTDecK/kN9DwjJzygaNyOzVCs
4OEbYH9Sylpfc2XCmM96lu/K1LyDXZhkfHaKaCz+USz1dBODJ/9JitwVwqhtkB7s
TnuZdUCMNQP+jgdGYz0hLZTVhfFqbPgkSSgZRK0wTHqo2RPCtZS22VIMtCCyA5DG
F6/ehw==
-----END CERTIFICATE-----
EOF

## Upgrading ubuntu to latest dist
apt-get update
apt-get dist-upgrade --yes

## Install packages
echo "Install packages"
apt-get install -y puppet-agent git  
service puppet stop
update-rc.d -f puppet remove

## Create certificates
echo "Moving certificates in place"
mkdir -p /etc/tradeshift/tls

mv /tmp/client.cert /etc/tradeshift/tls/client.cert
mv /tmp/client.key /etc/tradeshift/tls/client.key
mv /tmp/bwtsi_ca.cert /etc/tradeshift/tls/tradeshift_ca.cert
chmod 0444 /etc/tradeshift/tls/*.cert
chmod 0440 /etc/tradeshift/tls/*.key
chown root:root /etc/tradeshift/tls/*

echo "Making certificates available for puppet"
mkdir -p /etc/puppetlabs/puppet/ssl/private_keys
mkdir -p /etc/puppetlabs/puppet/ssl/certs
touch /etc/puppetlabs/puppet/ssl/certs/base.base.bwtsi.cn.pem
cat > /etc/puppetlabs/puppet/ssl/certs/base.base.bwtsi.cn.pem << EOF
-----BEGIN CERTIFICATE-----
MIIEkjCCA3qgAwIBAgICAPkwDQYJKoZIhvcNAQELBQAwga8xCzAJBgNVBAYTAkNO
MRAwDgYDVQQIEwdCZWlqaW5nMRAwDgYDVQQHEwdCZWlqaW5nMRswGQYDVQQKExJC
YWl3YW5nIFRyYWRlc2hpZnQxJzAlBgNVBAsTHkJhaXdhbmcgVHJhZGVzaGlmdCBF
bmdpbmVlcmluZzE2MDQGA1UEAxMtQmFpd2FuZyBUcmFkZXNoaWZ0IFJvb3QgQ2Vy
dGlmaWNhdGUgQXV0aG9yaXR5MB4XDTE3MDgxODAwMDAwMFoXDTIwMDgxNzIzNTk1
OVowgZQxCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRAwDgYDVQQHEwdC
ZWlqaW5nMRswGQYDVQQKExJCYWl3YW5nIFRyYWRlc2hpZnQxJzAlBgNVBAsTHkJh
aXdhbmcgVHJhZGVzaGlmdCBFbmdpbmVlcmluZzEbMBkGA1UEAxMSYmFzZS5iYXNl
LmJ3dHNpLmNuMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtDaBK1LL
1cAxiA0NwNfJVYc915dxDfhCN9eoX3gymWMrVLu5R3M7XakuIXGX6FDHj0VG5i2C
KofZQIV1eV1D9GYz9VWh9vvsclE93HGBgvyTg/IOfFH3D3ypMQrOfIzhM0KOnlYv
cYAQKFo0OKpO2Zp7O+2m4FeZ2tEu6/kdllhb7YIGmOb0mypJNkpBQ0omAWh2fAxO
dNyXuekr9RSCVlD+GWQkbN5A4+2atUi7b0IUpB1B9L2kIpWq8eotZSd6MpAAACrj
EWcB/2cde1iGKUxrJtaY8RYXKNUBqUWH8xj/Tl/q1oTjKsTXcyOjGEHcAOkMt4HE
ze4Tijo9AlbicQIDAQABo4HQMIHNMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFA7T
pbKPMF25Hn0vfqLdq43PDM5hMAsGA1UdDwQEAwIEsDAnBgNVHSUEIDAeBggrBgEF
BQcDAgYIKwYBBQUHAwcGCCsGAQUFCAICMDEGA1UdHwQqMCgwJqAkoCKGIGh0dHBz
Oi8vcGtpLmJ3dHNpLmNuL0JXVFNfQ0EuY3JsMDUGCCsGAQUFBwEBBCkwJzAlBggr
BgEFBQcwAYYZaHR0cHM6Ly9wa2kuYnd0c2kuY24vb2NzcDANBgkqhkiG9w0BAQsF
AAOCAQEAjsiLfsLzT/Zr6abfy4mXRxM/eGTZ150a/IGUoLmvdv3z4G/BbDwZeW57
BkLd6XXj/NVwZuh6ZDGR0CJ+FflaQNuBXXQGVTgdwjPMiR70o+rZIE2JG8TvhmxB
dJSOy7gnmzIHVoFI+Q980zrawS49oybhoroVvpFf+9lShEctS+V091Nz75b32Jbc
ZNf5OVp0ttuTJFLw05es6sx6wnJNQXICxmBx2qt8LfZk29i3/LgCA0Dp4HsFg1Tw
zFL1Pi7Y3lfJTe1+PFDU4BUrzIYzC5EX1vSl68SLeIQ/qYrzOralruvwZaorLJzk
b0sziE4awzH39fnYj4SsYfQ9emU9Yw==
-----END CERTIFICATE-----
EOF
touch /etc/puppetlabs/puppet/ssl/certs/cat_crt.pem
cat > /etc/puppetlabs/puppet/ssl/certs/cat_crt.pem << EOF
-----BEGIN CERTIFICATE-----
MIIEZjCCA06gAwIBAgIBATANBgkqhkiG9w0BAQsFADCBrzELMAkGA1UEBhMCQ04x
EDAOBgNVBAgTB0JlaWppbmcxEDAOBgNVBAcTB0JlaWppbmcxGzAZBgNVBAoTEkJh
aXdhbmcgVHJhZGVzaGlmdDEnMCUGA1UECxMeQmFpd2FuZyBUcmFkZXNoaWZ0IEVu
Z2luZWVyaW5nMTYwNAYDVQQDEy1CYWl3YW5nIFRyYWRlc2hpZnQgUm9vdCBDZXJ0
aWZpY2F0ZSBBdXRob3JpdHkwIBcNMTYwNTEzMTE0MDAwWhgPMjA2NjA1MTMxMTQw
MDBaMIGvMQswCQYDVQQGEwJDTjEQMA4GA1UECBMHQmVpamluZzEQMA4GA1UEBxMH
QmVpamluZzEbMBkGA1UEChMSQmFpd2FuZyBUcmFkZXNoaWZ0MScwJQYDVQQLEx5C
YWl3YW5nIFRyYWRlc2hpZnQgRW5naW5lZXJpbmcxNjA0BgNVBAMTLUJhaXdhbmcg
VHJhZGVzaGlmdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eTCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAMMMZB54Btgl6ZSbosQMT0VrKDt7m+vOkuni
7VBJSyz5BAV6lqPrfbFcXxSMBPbDVdtjBnJe/nn+0W3jOySZhH1D+QEJKYwZWUF5
5KhZOMUmH0XJcIEjbKlG4ljsp0MZKYpO49HUGfhxmx8HofB+vmlnDn0ft1X/QaNy
9wjIz8+fjpD3rtmOAKD5bshJQd4X8RsZtFmzSjN4TgXD3GIcz+ua1MmP4Y90B0dt
1qPgJVZ2aDgKRBt01ccsB5N8l2R3E0L6T9FEFgUzHn6IP+HCX/ChlDMINw4kIUbD
PObVRAIPmKRTD69Jlg8VzZyztRI9Bu/xvqY5HU/NMyW/PywqvSMCAwEAAaOBiDCB
hTAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIBhjAxBgNVHR8EKjAoMCagJKAihiBo
dHRwczovL3BraS5id3RzaS5jbi9CV1RTX0NBLmNybDA1BggrBgEFBQcBAQQpMCcw
JQYIKwYBBQUHMAGGGWh0dHBzOi8vcGtpLmJ3dHNpLmNuL29jc3AwDQYJKoZIhvcN
AQELBQADggEBAISFBd43KSbfPa+O4GlP5uxzuovF+XWusMGkR7IninlfAb9ENKJD
g/C0uPWZyYwBXcHbiUFCBmFgeJ1F1wkNqjptRjcCFZS5D+mh0wKKR1A5m04Ilqf3
DqFc2Kd0XlOs/lcW5hjY1Br74SdJ/1HWfcqrp8C9oXH5Dpyb0CPJlGzLVBprp1Ej
Ey5AMAxyrArJH3t575RJ5Wa3FDYYoiIUw6YNyZhYRyMD2uj56ZuZlIk5TFpDxQfd
ylCXTswL/KjtXL9QeZGfSehsVsSfvldZ/oqQjZEt5D1CUWoFy4l3NVcJJFTxjgQ5
M2Rl9BnCW086nGEFFgtKv5F7icdL7BrSQg4=
-----END CERTIFICATE-----
EOF
touch /etc/puppetlabs/puppet/ssl/certs/ca.pem
cat > /etc/puppetlabs/puppet/ssl/certs/ca.pem << EOF
-----BEGIN CERTIFICATE-----
MIIEZjCCA06gAwIBAgIBATANBgkqhkiG9w0BAQsFADCBrzELMAkGA1UEBhMCQ04x
EDAOBgNVBAgTB0JlaWppbmcxEDAOBgNVBAcTB0JlaWppbmcxGzAZBgNVBAoTEkJh
aXdhbmcgVHJhZGVzaGlmdDEnMCUGA1UECxMeQmFpd2FuZyBUcmFkZXNoaWZ0IEVu
Z2luZWVyaW5nMTYwNAYDVQQDEy1CYWl3YW5nIFRyYWRlc2hpZnQgUm9vdCBDZXJ0
aWZpY2F0ZSBBdXRob3JpdHkwIBcNMTYwNTEzMTE0MDAwWhgPMjA2NjA1MTMxMTQw
MDBaMIGvMQswCQYDVQQGEwJDTjEQMA4GA1UECBMHQmVpamluZzEQMA4GA1UEBxMH
QmVpamluZzEbMBkGA1UEChMSQmFpd2FuZyBUcmFkZXNoaWZ0MScwJQYDVQQLEx5C
YWl3YW5nIFRyYWRlc2hpZnQgRW5naW5lZXJpbmcxNjA0BgNVBAMTLUJhaXdhbmcg
VHJhZGVzaGlmdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eTCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAMMMZB54Btgl6ZSbosQMT0VrKDt7m+vOkuni
7VBJSyz5BAV6lqPrfbFcXxSMBPbDVdtjBnJe/nn+0W3jOySZhH1D+QEJKYwZWUF5
5KhZOMUmH0XJcIEjbKlG4ljsp0MZKYpO49HUGfhxmx8HofB+vmlnDn0ft1X/QaNy
9wjIz8+fjpD3rtmOAKD5bshJQd4X8RsZtFmzSjN4TgXD3GIcz+ua1MmP4Y90B0dt
1qPgJVZ2aDgKRBt01ccsB5N8l2R3E0L6T9FEFgUzHn6IP+HCX/ChlDMINw4kIUbD
PObVRAIPmKRTD69Jlg8VzZyztRI9Bu/xvqY5HU/NMyW/PywqvSMCAwEAAaOBiDCB
hTAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIBhjAxBgNVHR8EKjAoMCagJKAihiBo
dHRwczovL3BraS5id3RzaS5jbi9CV1RTX0NBLmNybDA1BggrBgEFBQcBAQQpMCcw
JQYIKwYBBQUHMAGGGWh0dHBzOi8vcGtpLmJ3dHNpLmNuL29jc3AwDQYJKoZIhvcN
AQELBQADggEBAISFBd43KSbfPa+O4GlP5uxzuovF+XWusMGkR7IninlfAb9ENKJD
g/C0uPWZyYwBXcHbiUFCBmFgeJ1F1wkNqjptRjcCFZS5D+mh0wKKR1A5m04Ilqf3
DqFc2Kd0XlOs/lcW5hjY1Br74SdJ/1HWfcqrp8C9oXH5Dpyb0CPJlGzLVBprp1Ej
Ey5AMAxyrArJH3t575RJ5Wa3FDYYoiIUw6YNyZhYRyMD2uj56ZuZlIk5TFpDxQfd
ylCXTswL/KjtXL9QeZGfSehsVsSfvldZ/oqQjZEt5D1CUWoFy4l3NVcJJFTxjgQ5
M2Rl9BnCW086nGEFFgtKv5F7icdL7BrSQg4=
-----END CERTIFICATE-----
EOF
touch /etc/puppetlabs/puppet/ssl/certs/false.pem
cat > /etc/puppetlabs/puppet/ssl/certs/false.pem << EOF
-----BEGIN CERTIFICATE-----
MIIEkjCCA3qgAwIBAgICAPkwDQYJKoZIhvcNAQELBQAwga8xCzAJBgNVBAYTAkNO
MRAwDgYDVQQIEwdCZWlqaW5nMRAwDgYDVQQHEwdCZWlqaW5nMRswGQYDVQQKExJC
YWl3YW5nIFRyYWRlc2hpZnQxJzAlBgNVBAsTHkJhaXdhbmcgVHJhZGVzaGlmdCBF
bmdpbmVlcmluZzE2MDQGA1UEAxMtQmFpd2FuZyBUcmFkZXNoaWZ0IFJvb3QgQ2Vy
dGlmaWNhdGUgQXV0aG9yaXR5MB4XDTE3MDgxODAwMDAwMFoXDTIwMDgxNzIzNTk1
OVowgZQxCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRAwDgYDVQQHEwdC
ZWlqaW5nMRswGQYDVQQKExJCYWl3YW5nIFRyYWRlc2hpZnQxJzAlBgNVBAsTHkJh
aXdhbmcgVHJhZGVzaGlmdCBFbmdpbmVlcmluZzEbMBkGA1UEAxMSYmFzZS5iYXNl
LmJ3dHNpLmNuMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtDaBK1LL
1cAxiA0NwNfJVYc915dxDfhCN9eoX3gymWMrVLu5R3M7XakuIXGX6FDHj0VG5i2C
KofZQIV1eV1D9GYz9VWh9vvsclE93HGBgvyTg/IOfFH3D3ypMQrOfIzhM0KOnlYv
cYAQKFo0OKpO2Zp7O+2m4FeZ2tEu6/kdllhb7YIGmOb0mypJNkpBQ0omAWh2fAxO
dNyXuekr9RSCVlD+GWQkbN5A4+2atUi7b0IUpB1B9L2kIpWq8eotZSd6MpAAACrj
EWcB/2cde1iGKUxrJtaY8RYXKNUBqUWH8xj/Tl/q1oTjKsTXcyOjGEHcAOkMt4HE
ze4Tijo9AlbicQIDAQABo4HQMIHNMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFA7T
pbKPMF25Hn0vfqLdq43PDM5hMAsGA1UdDwQEAwIEsDAnBgNVHSUEIDAeBggrBgEF
BQcDAgYIKwYBBQUHAwcGCCsGAQUFCAICMDEGA1UdHwQqMCgwJqAkoCKGIGh0dHBz
Oi8vcGtpLmJ3dHNpLmNuL0JXVFNfQ0EuY3JsMDUGCCsGAQUFBwEBBCkwJzAlBggr
BgEFBQcwAYYZaHR0cHM6Ly9wa2kuYnd0c2kuY24vb2NzcDANBgkqhkiG9w0BAQsF
AAOCAQEAjsiLfsLzT/Zr6abfy4mXRxM/eGTZ150a/IGUoLmvdv3z4G/BbDwZeW57
BkLd6XXj/NVwZuh6ZDGR0CJ+FflaQNuBXXQGVTgdwjPMiR70o+rZIE2JG8TvhmxB
dJSOy7gnmzIHVoFI+Q980zrawS49oybhoroVvpFf+9lShEctS+V091Nz75b32Jbc
ZNf5OVp0ttuTJFLw05es6sx6wnJNQXICxmBx2qt8LfZk29i3/LgCA0Dp4HsFg1Tw
zFL1Pi7Y3lfJTe1+PFDU4BUrzIYzC5EX1vSl68SLeIQ/qYrzOralruvwZaorLJzk
b0sziE4awzH39fnYj4SsYfQ9emU9Yw==
-----END CERTIFICATE-----
EOF


/bin/cp -af /etc/tradeshift/tls/client.key /etc/puppetlabs/puppet/ssl/private_keys/${ROLE}.${ENVIRONMENT}.bwtsi.cn.pem
# chown puppet:puppet /etc/puppetlabs/puppet/ssl -R

## Configure puppet
echo "Configure puppet"
mv /tmp/puppet.conf /etc/puppetlabs/puppet/puppet.conf
chmod 0644 /etc/puppetlabs/puppet/puppet.conf
chown root:root /etc/puppetlabs/puppet/puppet.conf

## Run Puppet
set +e
echo "Running puppet"
/opt/puppetlabs/puppet/bin/puppet agent --onetime --verbose --no-daemonize
result=$?
case $result in
0)
  echo "The run succeeded with no changes or failures; the system was already in the desired state."
  ;;
1)
  echo "The run failed, or wasn't attempted due to another run already in progress."
  exit 1;
  ;;
2)
  echo "The run succeeded, and some resources were changed."
  ;;
4)
  echo "The run succeeded, and some resources failed."
  exit 4;
  ;;
6)
  echo "The run succeeded, and included both changes and failures."
  exit 6;
  ;;
*)
  echo "Unknown puppet exit code: $result"
  exit $result
  ;;
esac
set -e

alias puppet-run='sudo /opt/puppetlabs/bin/puppet agent --test'

## Cleaning
echo "Cleaning up - autoclean"
apt-get autoclean
echo "Cleaning up - autoremove"
apt-get autoremove
echo "Cleaning up - update"
apt-get update

# install nodejs
mkdir -p /var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation
cd /var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation
wget https://npm.taobao.org/mirrors/node/v6.11.4/node-v6.11.4-linux-x64.tar.gz
tar zxvf node-v6.11.4-linux-x64.tar.gz
mv node-v6.11.4-linux-x64 nodejs-6.11.4
chown jenkins:jenkins -R /var/lib/jenkins/tools
rm -rf node-v6.11.4-linux-x64.tar.gz
